---
- name: attach_disk | Gather new volumes information 
  uri:
    url: 'https://{{ powervc_url}}:9000/v3/{{ TENANTID }}/volumes'
    method: GET
    use_proxy: no
    validate_certs: no
    return_content: no
    headers:
      X-Auth-Token: "{{ TOKEN }}"
  register: volumes_info

- name: attach_disk | Get new disks volume IDs
  set_fact:
    disk_ids:
      "{{ disk_ids | default([]) + [ volumes_info['json']['volumes'] | json_query(query) ] }}"
  vars:
    query: "[?name=='{{ item }}'].id | [0]"
  with_items:
    - "{{ disk_names }}"

- name: attach_disk | Gather disk WWN ID
  uri:
    url: 'https://{{ powervc_url}}:9000/v3/{{ TENANTID }}/volumes/{{ item }}'
    method: GET
    use_proxy: no
    validate_certs: no
    return_content: no
    headers:
      X-Auth-Token: "{{ TOKEN }}"
  register: disks_wwn_out
  with_items:
    - "{{ disk_ids }}"
  no_log: True

- name: attach_disk | Prepare disk WWN ID variable
  set_fact:
    disk_info_pvc:
      disk_wwn:
        "{{ disk_wwn | default([]) + [ item.json.volume.metadata.volume_wwn ]  }}"
      disk_pvc_name:
        "{{ disk_pvc_name | default([]) + [ item.json.volume.name ] }}"
  with_items:
    - "{{ disks_wwn_out['results'] }}"    
  register: disk_info_pvc
  no_log: True

- name: attach_disk | Set disk WWN ID variable
  set_fact:
    powervc_vm_disk_info:
      "{{ powervc_vm_disk_info | default([]) + [ item.ansible_facts.disk_info_pvc ] }}"
  with_items:
    - "{{ disk_info_pvc['results'] }}"
      # - "{{ disk_info_pv c}}"
  no_log: True

- name: attach_disk | Attach volumes to AIX VMs | This task may take a while
  uri:
    url: 'https://{{ powervc_url }}/powervc/openstack/compute/v2.1/{{ TENANTID }}/servers/{{ item[1] }}/action'
    method: POST
    validate_certs: no
    headers:
      X-Auth-Token: "{{ TOKEN }}"
    body_format: json
    body: >
      {"bulkVolumeAttach":{"volumeAttachment":[{"volumeId":"{{ item[0] }}","device":null,"is_boot_volume":"False"}]}}
    return_content: yes
    status_code: 202
  register: disk_creation
  with_nested:
    - "{{ disk_ids }}"
    - "{{ vms_vmid }}"
  loop_control:
    pause: 6

- name: attach_disk | Sleeping 10 seconds for disk attach ends
  pause:
    seconds: 10
